[package]
name = "novel2audiobook"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
tokio-tungstenite = { version = "0.21", features = ["rustls-tls-native-roots"] }
futures = "0.3"
uuid = { version = "1.7", features = ["v4"] }
inquire = "0.7"
anyhow = "1.0"
regex = "1.10"
url = "2.5"
log = "0.4"
env_logger = "0.11"
async-trait = "0.1.89"
chrono = "0.4.43"
